### ISSUE TITLE
Why is rversions in Suggests?

### ISSUE THREAD

**Issue by maelle** [sagiegurari/scriptexec#31]
I see `rversions` is listed among `Suggests` dependencies but I don't see where it is used in the package code, is it actually needed?

**Comment by sagiegurari** [comment]
thats actually a good question. figured it came from some dependency. 
lets me check it and at same time upgrade all dependencies.

**Comment by sagiegurari** [comment]
pushed some updates to branch 0.3.1
you can review there the updated dependencies

**Comment by maelle** [comment]
Thanks!

**Comment by sagiegurari** [comment]
0.3.1 released

**Comment by maelle** [comment]
🎉
